export const TOKENS = {
  USDC: {
    address: "0x9c8fa1ee532f8afe9f2e27f06fd836f3c9572f71",
    decimals: 6,
    ens_address: "",
    logo: {
      height: "",
      ipfs_hash: "",
      src: "",
      width: "",
    },
    name: "USD//Coin",
    social: {
      blog: "",
      chat: "",
      facebook: "",
      forum: "",
      github: "https://github.com/centrehq/centre-tokens",
      gitter: "",
      instagram: "",
      linkedin: "",
      reddit: "",
      slack: "",
      telegram: "",
      twitter: "",
      youtube: "",
    },
    support: {
      email: "",
      url: "https://www.centre.io",
    },
    symbol: "USDC",
    website: "https://www.centre.io",
  },
  USDT: {
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    decimals: 6,
    ens_address: "",
    logo: {
      height: 28,
      ipfs_hash: "",
      src: "https://etherscan.io/token/images/tether28_2.png",
      width: 28,
    },
    name: "USD Tether (erc20)",
    social: {
      blog: "",
      chat: "",
      facebook: "",
      forum: "",
      github: "",
      gitter: "",
      instagram: "",
      linkedin: "",
      reddit: "",
      slack: "",
      telegram: "",
      twitter: "https://twitter.com/tether_to",
      youtube: "",
    },
    support: {
      email: "billy@tether.to",
      url: "",
    },
    symbol: "USDT",
    website: "https://tether.to",
  },
  WBTC: {
    address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    decimals: 8,
    ens_address: "",
    logo: {
      height: 48,
      ipfs_hash: "",
      src: "https://www.wbtc.network/assets/BitGo-favicon.ico",
      width: 48,
    },
    name: "Wrapped Bitcoin",
    social: {
      blog: "",
      chat: "",
      facebook: "",
      forum: "",
      github: "https://github.com/WrappedBTC",
      gitter: "",
      instagram: "",
      linkedin: "",
      reddit: "",
      slack: "",
      telegram: "",
      twitter: "",
      youtube: "",
    },
    support: {
      email: "",
      url: "",
    },
    symbol: "WBTC",
    website: "https://wbtc.network",
  },
  DAI: {
    address: "0xaD6D458402F60fD3Bd25163575031ACDce07538D",
    decimals: 18,
    ens_address: "",
    logo: {
      height: "",
      ipfs_hash: "",
      src: "",
      width: "",
    },
    name: "Dai Stablecoin v2.0",
    social: {
      blog: "",
      chat: "https://chat.makerdao.com",
      facebook: "",
      forum: "",
      github: "https://github.com/makerdao",
      gitter: "",
      instagram: "",
      linkedin: "",
      reddit: "https://www.reddit.com/r/MakerDAO",
      slack: "",
      telegram: "",
      twitter: "https://twitter.com/MakerDAO",
      youtube: "",
    },
    support: {
      email: "support@makerdao.com",
      url: "https://chat.makerdao.com",
    },
    symbol: "DAI",
    website: "https://makerdao.com",
  },
  UNI: {
    address: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    decimals: 18,
    ens_address: "",
    logo: {
      height: "250",
      ipfs_hash: "",
      src: "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png",
      width: "250",
    },
    name: "Uniswap",
    social: {
      blog: "https://uniswap.org/blog/",
      chat: "https://discord.com/invite/XErMcTq",
      facebook: "",
      forum: "",
      github: "",
      gitter: "",
      instagram: "",
      linkedin: "",
      reddit: "",
      slack: "https://discord.com/invite/XErMcTq",
      telegram: "",
      twitter: "https://twitter.com/UniswapProtocol",
      youtube: "",
    },
    support: {
      email: "",
      url: "",
    },
    symbol: "UNI",
    type: "ERC20",
    website: "https://uniswap.org/",
  },
  FRAX: {
    address: "0x853d955acef822db058eb8505911ed77f175b99e",
    decimals: 18,
    ens_address: "",
    logo: {
      height: "250",
      ipfs_hash: "",
      src: "https://etherscan.io/token/images/fraxfinance_32.png",
      width: "250",
    },
    name: "Frax",
    social: {},
    support: {
      email: "",
      url: "",
    },
    symbol: "FRAX",
    type: "ERC20",
    website: "https://frax.finance/",
  },
  PAX: {
    address: "0x8E870D67F660D95d5be530380D0eC0bd388289E1",
    decimals: 18,
    ens_address: "",
    logo: {
      height: "120",
      ipfs_hash: "",
      src: "https://static.standard.paxos.com/logos/square_120_120.png",
      width: "120",
    },
    name: "Paxos Standard (PAX)",
    social: {
      blog: "https://www.paxos.com/news-blogs/engineering/",
      chat: "",
      facebook: "",
      forum: "",
      github: "https://github.com/paxosglobal",
      gitter: "",
      instagram: "",
      linkedin: "https://www.linkedin.com/company/paxos",
      reddit: "",
      slack: "",
      telegram: "",
      twitter: "https://twitter.com/paxosglobal",
      youtube: "",
    },
    support: {
      email: "help@paxos.com",
      url: "https://www.paxos.com/contact/",
    },
    symbol: "PAX",
    type: "ERC20",
    website: "https://www.paxos.com/standard",
  },
  "LINK (Chainlink)": {
    address: "0x514910771af9ca656af840dff83e8264ecf986ca",
    decimals: 18,
    ens_address: "",
    logo: {
      height: "",
      ipfs_hash: "",
      src: "",
      width: "",
    },
    name: "LINK Chainlink",
    social: {
      blog: "",
      chat: "",
      facebook: "",
      forum: "",
      github: "",
      gitter: "",
      instagram: "",
      linkedin: "",
      reddit: "",
      slack: "https://chainlinknetwork.slack.com",
      telegram: "",
      twitter: "",
      youtube: "",
    },
    support: {
      email: "support@smartcontract.com",
      url: "",
    },
    symbol: "LINK (Chainlink)",
    website: "https://link.smartcontract.com",
  },
};
